### ISSUE TITLE
Feature Request: relative_reader with max length?

### ISSUE THREAD

**Issue by bramp** [irauta/bitreader#16]
When parsing a stream, it is common to have length prefixed data. I would love to be able to call relative_reader with this length, and pass the result to another function responsible for parsing the data. Having the length encoded in the bitreader would greatly simplify bound checking.

Thoughts?

**Comment by irauta** [comment]
Good idea! I figure that the new function would take the length as bytes and would require the reader to be at a byte-aligned position. (Are there even formats that have the length prefixes in bits instead of eight-bit bytes?) The returned reader could then just work on a limited slice of the original buffer so the actual reading code could be kept as-is.

I want to keep things backwards compatible, so there'd have to be a new error enum for signaling that too much data was requested or that the position is not byte-aligned. The latter wouldn't make sense for the current reading fns either.

The alignment error should contain the current position in bits (being in line with the currently existing error type) but the "not enough data left in slice" error seems like it would better be expressed in bytes. Hm, maybe `NotEnoughData { position_bytes: usize, remaining_bytes: usize, requested_bytes: usize }` to make the used units explicit? The requested_bytes field is not really necessary, but would again be in line with the contents of the currently existing NotEnoughData error variant.

Is this compatible with what you had in mind?

**Comment by bramp** [comment]
I actually requested this, because I was solving problems on Advent of Code, and their puzzle was not byte aligned. Now I'm not sure how often non-byte alignment happens in real life.

So ideally it would allow arbitrary alignment.

Looking over the code, it seems easy to change anywhere it computes the length (with len()/8) with a remaining bits field. 

I'd be happy to send you a pull request with the changes.

**Comment by irauta** [comment]
I originally made this lib because I was looking into decoding DVB transport streams, and the format seemed to be surprisingly byte-aligned (for example, see the table on page 17 of [this PDF](https://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.04.01_40/en_300468v010401o.pdf), where the adjacent field lengths tend to add up to 8/16/etc.), but I don't have wider experience of densely packed binary formats. I'd like to primarily support real-world use cases, so I'm feeling a little undecided...even though support for limiting reads to bit-level ranges does imply support for byte-level ranges too.

**Comment by bramp** [comment]
I've decoded a bunch of file formats in my past, and any time I saw some kind of sub-message/packet the beginning was always byte aligned, but the end might have had padding. I quickly searched Google, and I can't find any real work examples where the beginning isn't aligned. However, that doesn't mean they don't exists.

Is the only argument to keep the relative_reader byte aligned for simplicity/performance?

**Comment by irauta** [comment]
I thought about this, and in the end the only arguments I'd have for this feature being byte-based is implementation simplicity (in the sense of what changes need to be made to current code) and usage ergonomics (no need to use `* 8` when making the relative reader when the format gives lengths in bytes). However, there should be only a few changes needed for the bit-based version too, and the `* 8` part doesn't ultimately sound like that big of an issue, and as you said, there might be formats that would benefit from the bit-level granularity, so yeah, lets go with the entirely bit-level version.

**Comment by irauta** [comment]
Great, thank you! I'll push a new version to crates.io in a moment.
