### ISSUE TITLE
Crash with wrong parameter (read 0 bits)

### ISSUE THREAD

**Issue by hfiguiere** [irauta/bitreader#18]
The following code crashes (default debug target) with `thread 'main' panicked at 'attempt to subtract with overflow', /Users/hub/.cargo/registry/src/github.com-1ecc6299db9ec823/bitreader-0.3.5/src/lib.rs:320:36`

```javascript
extern crate bitreader;

use bitreader::BitReader;

fn main() {
    let buf = vec![10, 20, 30, 40];

    let mut bits = BitReader::new(&buf);

    let zero = bits.read_i32(0).expect("can't read bits");

    println!("zero {}", zero);
}
```

I think it should return an error instead.

**Comment by irauta** [comment]
Thanks for the report! A crash is definitely not okay, the intended behavior when reading zero bits is returning a zero and doing nothing else. It's even covered by a test...except the test only checks reading an unsigned value. The culprit here seems to be in the signed value code which doesn't check for the zero bits case like the unsigned code does. I'll make a fix and publish it on crates.io soon.

**Comment by irauta** [comment]
Fixed version is now up.
