### ISSUE TITLE
Remaining bits of the relative reader seems shorter than expected.

### ISSUE THREAD

**Issue by Tackoil** [irauta/bitreader#22]
Hello, all. 

I'm writing a bit-wise parser tool. And I found out a strange behavior as the following case.

```rust
#[test]
fn relative_reader_remaining() {
    let bytes = &[0b0001_0010, 0b0011_0100];
    let mut reader = BitReader::new(bytes);
    reader.skip(2).unwrap();
    let relative_reader = reader.relative_reader();
    assert_eq!(reader.remaining(), relative_reader.remaining());
}
```
As a fact, It'll not pass the test. The remaining bits in relative one will be always shorter than the original reader. And the relative reader cannot really touch the end of the bit stream.

After reviewing the source code, field `relative_offset` in struct `BitReader` seems to be the root cause [link](https://github.com/irauta/bitreader/blob/79ededce824f9837e38344f346bfd718b9eb02ac/src/lib.rs#L73C1-L73C26). But I'm not quite understand the usage of this field. In my opinion, it could be removed to resolve the case above.

**Comment by irauta** [comment]
Thanks for the clear bug report! The problem was in `remaining()` which returned a wrong value when using a relative reader (that was created after some bits have already been read or skipped). Most of the reading methods do not rely on `remaining()`, so they should have worked regardless of this bug. The `read_u8_slice()` method was an exception to this.

I just published a new version of the crate that should have the bug fixed, and added a test that's a slightly changed version of your example case.

The position tracking for a reader returned by `relative_reader()` starts at zero regardless of how much data the original reader has already consumed. This is meant to allow splitting reading code into somewhat independent logical pieces, for example for a data structure's header and body. The body reading code might want to know how much it has already read without caring about to the header size, and the "fresh start" is meant to help with that. The `relative_offset` field is what makes this possible. (It could be removed, if creating relative readers were allowed only at byte aligned positions, but that would be a breaking change.)
